import type {Metadata} from "next";

import Link from "next/link";

import { ApolloWrapper } from "@/graphql/apollo-wrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "{{name}}",
  description: "Generated by carlos medina",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="dark container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4 font-sans antialiased">
        <header className="text-xl font-bold leading-[4rem]">
          <Link href="/">{{name}}</Link>
        </header>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
